#!/command/with-contenv sh
cd /workspace
export HOME=/home/claude
export WORKSPACES_ROOT=/workspace
export NODE_OPTIONS="${NODE_OPTIONS:+$NODE_OPTIONS }--no-deprecation"
export PATH="/home/claude/.bun/install/global/node_modules/.bin:${PATH}"

exec s6-setuidgid claude bunx @cloudcli-ai/cloudcli --port 3001 
# cd /home/claude/.claude-code-ui/plugins/project-stats
# exec s6-setuidgid claude  bun install && bun run build 